// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqUmXGosIqWHAu3c4Wiq6p2GhAnOHZ2og',
    appId: '1:854574072972:web:77fea66223a605c0afa7a9',
    messagingSenderId: '854574072972',
    projectId: 'stackbuld-e4397',
    authDomain: 'stackbuld-e4397.firebaseapp.com',
    storageBucket: 'stackbuld-e4397.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxq7a7Z_u8NG-n9QnFF1tMptnXVrCS0ws',
    appId: '1:854574072972:android:b9eb15e88a3d6a21afa7a9',
    messagingSenderId: '854574072972',
    projectId: 'stackbuld-e4397',
    storageBucket: 'stackbuld-e4397.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfK6pDxP91GFDKx1GOCVkkAsNR8IVORyI',
    appId: '1:854574072972:ios:c82b4bb72383ff19afa7a9',
    messagingSenderId: '854574072972',
    projectId: 'stackbuld-e4397',
    storageBucket: 'stackbuld-e4397.appspot.com',
    iosBundleId: 'stackbuld.stackbuld',
  );
}
